---
dependency:
  name: galaxy
  options:
    role-file: molecule/default/requirements.yml
    requirements-file: requirements.yml

driver:
  name: docker

platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian13}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      # Mount Docker storage to a volume to facilitate use of overlay2 driver
      - /var/lib/docker
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

ansible:
  cfg:
    defaults:
      callbacks_enabled: profile_tasks
      inject_facts_as_vars: false

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        restic_rest_server_password: foo
        project_dir: ${MOLECULE_PROJECT_DIRECTORY}

scenario:
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
